import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import WidgetSide from "@/components/WidgetSide";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" >
      <body className="min-h-screen bg-gray-50 text-gray-900">
      <div className="max-w-7xl mx-auto flex">
          <Sidebar />
          <main className={`flex-1 max-w-3xl bg-white`}>
              {children}
          </main>
          <WidgetSide/>
      </div>

      </body>
    </html>
  );
}
